### ISSUE TITLE
When using batch mode, I seem to be unable to use the S3 Hadoop plugin to query my bucket.

### ISSUE THREAD

**Issue by ranoble** [getindata/streaming-jupyter-integrations#79]
Only for more complex jobs, only in batch mode.

Connect
```
%flink_connect \
    --execution-target remote \
    --execution-mode batch \
    --remote-hostname [server] \
    --remote-port 8081
```

Create simple table.
```
%%flink_execute_sql

CREATE TABLE `person` (
  `uuid` VARCHAR(2147483647),
  `name` ARRAY<ROW<`text` VARCHAR(2147483647), `family` VARCHAR(2147483647), `given` ARRAY<VARCHAR(2147483647)>>>,
  `gender` VARCHAR(2147483647),
  `birthDate` ROW<`instant` TIMESTAMP(6), `utcOffset` VARCHAR(2147483647)>,
) WITH (
  'path' = 's3a://my_bucket/person/',
  'connector' = 'filesystem',
  'format' = 'orc'
)
```
 I can read this, which is strange, because
```

%%flink_execute_sql
CREATE TABLE `person_2` WITH (
  'path' = 's3a://my_bucket/person_2/',
  'connector' = 'filesystem',
  'format' = 'orc'
) AS SELECT * from `person`;
``` fails with an UnsupportedFileSystemSchemeException: Could not find a file system implementation for scheme 's3a'.

I've installed the hadoop libraries, hooked up the environment variables etc. I've also added the plugin to the 'plugins' folder in the pyflink install. 

Any ideas would be most welcome...

**Comment by grzegorz8** [comment]
Hi! Where have you added this library precisely? I suspect you added them on Flink nodes only. The Jupyter notebook extension creates and maintains `StreamExecutionEnvironment`, so I believe you need to add these dependencies (or only a part of it - hard to tell which ones precisely) to the container/machine where Jupyter Notebook runs. Usually, the path is something like this `<some-prefix>/python3.8/site-packages/pyflink/lib`.

**Comment by ranoble** [comment]
I've added it in the <some-prefix>/python3.8/site-packages/pyflink/plugins/s3/flink-s3-fs-hadoop-1.16.0.jar.

**Comment by niladrem** [comment]
Hi! Adding jars to plugins sometimes doesn't work. Please try to add this jar to the PyFlink lib directory. You can also try to use `%flink_register_jar` but I don't know if it will work with remote target.

**Comment by ranoble** [comment]
Thanks, we're trying both.

**Comment by ranoble** [comment]
Fixed, thanks all. Looks like the lib sorted it. Am unsure on the effect on running locally, but remotely works well
